### ISSUE TITLE
Please add a zip file to the assets containing all assets file except source

### ISSUE THREAD

**Issue by c33s** [cyd01/KiTTY#68] opened 2019-11-06 15:51 UTC
as on th putty page where i can download a `putty.zip` it would be nice to be able to download a kitty.zip which contains all exe files

**Comment by r15ch13** [comment] 2019-11-07 20:51
Adding a zipfile would also make the automated update process for Scoop easier.
Currently, we have to update it manually every time.
https://github.com/lukesampson/scoop-extras/blob/master/bucket/kitty.json

**Comment by cyd01** [comment] 2019-12-11 13:25
On the official web site you can find this file: [https://www.9bis.net/kitty/files/kitty-bin-0.73.1.2.zip](https://www.9bis.net/kitty/files/kitty-bin-0.73.1.2.zip)

**Comment by r15ch13** [comment] 2019-12-11 13:57
@cyd01 this zip file seems to be damaged and can't be extract with windows explorer or 7-zip 😢 

![image](https://user-images.githubusercontent.com/432127/70627388-71b14780-1c26-11ea-9076-4ee3d73b17e9.png)
![image](https://user-images.githubusercontent.com/432127/70627414-7b3aaf80-1c26-11ea-9476-e8709f55f89c.png)

**Comment by c33s** [comment] 2019-12-11 14:13
also can't extract it with total commander.

and from my side also the request to put it on the release page on github.

**Comment by cyd01** [comment] 2019-12-11 15:00
I don't know what was wrong with the last transfer. Sorry for that.
I've retransfered everything: zip and binaries files.

**Comment by c33s** [comment] 2019-12-11 16:17
@cyd01  may i ask you to reopen the ticket for the request to add the zip file to the release on github or should i open a new ticket or is it a wont-fix for you?

**Comment by AntonOks** [comment] 2020-01-17 20:05
@cyd01 
Talking about scoop... I've recently discovered that (**sometimes**?!??) there is a new KiTTY release including a ZIP file with the other brother-and-sister-tools on GitHub now... [btw., THANS for this, I've now enabled scoop's "autoupdate" feature](https://github.com/lukesampson/scoop-extras/commit/1d738525517a3ff531256cce1384d3b56f6e523f)

But sometimes there is no updated "release" (incl. a ZIP file) on GitHub BUT [the "**version.h**", the "/windows/***release***" files are updated](https://github.com/cyd01/KiTTY/commit/b6979abd1877b856ba4a3f0532f55c78d1d43048), a new "tag" was set AND a new download is available on [fosshub](https://www.fosshub.com/KiTTY.html?dwl=kitty-0.73.2.1.exe).

**_Question:_** Why is not every new KiTTY version shown on GitHub releases?

**Comment by cyd01** [comment] 2020-01-19 11:03
You are rugby
The upload process to github seems to fail.
I’ll upload it again when i’ll be at work
Please note that the official download page is at fosshub.com (see KiTTY
web site)

Le ven. 17 janv. 2020 à 21:05, Anton Oks <notifications@github.com> a
écrit :

**Comment by AntonOks** [comment] 2020-01-20 18:46
THANKS, autoupdate worked fine now...

I thought about using the fosshub binary for the scoop autoupdates, but assumed an KiTTY update will always also trigger an new available "full suite ZIP" on GitHub... and I just prefer to update everything at once, if possible ;)

Btw., THANKS for this great tool. I've switched from PuTTY some years ago and use it as "build-in replacement" in SuperPUTTY every single day... and also sometimes "native as is" because of the great extensions / additions compared to PuTTY...

>

**Comment by lars18th** [comment] 2020-02-12 10:54
Hi @AntonOks ,

If the issue is resolved, please close it.
Thank you!

**Comment by AntonOks** [comment] 2020-02-13 16:11
> Hi @AntonOks ,
> 
> If the issue is resolved, please close it.
> Thank you!

@lars18th cannot... guess this is left for @c33s as he opened it?!

**Comment by lars18th** [comment] 2020-02-13 17:20
> @lars18th cannot... guess this is left for @c33s as he opened it?!

Sorry! Yes, the issue is created by @c33s . I hope he wants to close it. If not, then @cyd01 can close it too, as I see that the problem is fixed.

Regards.

**Closed** 2020-02-13 20:38 UTC
