### ISSUE TITLE
[bug] System menuitems in System menu (Alt + Space) doen't work in 0.73.2.6

### ISSUE THREAD

**Issue by kissglay** [cyd01/KiTTY#135] opened 2020-03-14 19:41 UTC
These menuitems are not working in 0.73.2.6.
![2020-03-15_03 36 53 203](https://user-images.githubusercontent.com/529385/76689228-bb1e9200-666e-11ea-92f4-7450220315e7.png)

**Comment by systemmonkey42** [comment] 2020-03-14 23:37
Duplicate of #132, should be fixed in 0.73.2.7

**Comment by lars18th** [comment] 2020-03-19 07:33
Hi @cyd01 ,

After more testing, I feel is preferable to enable *by default* the option "System menu appears on ALT-Space" in the Window/Behaviour section of the Configuration. All my saved sessions have this disabled, and it's a pain to change one-by-one. So I suggest to enable it by default.

Please, @cyd01 & @systemmonkey42 , what do you think?

**Closed** 2020-03-19 07:35 UTC

**Comment by systemmonkey42** [comment] 2020-03-19 23:23
With the system menu on 'Alt-Space' option disabled, the alt-space key combination sends `<Esc><space>` to the terminal application.   Bash for example uses that key combination for the 'set-mark' command, other applications might also use it.  (Users might have VIM mappings for it for example).

While personally, having it default to on is preferrable, (and I DO have it on by default and in all session configurations), it is a change which may impact some users unexpectedly.

**Comment by lars18th** [comment] 2020-03-20 07:25
Hi @systemmonkey42 ,

OK. Good argument to not change it. Then, from my point of view this issue is resolved. :+1: 

Thank you!
