### ISSUE TITLE
[Bug] Kageant (0.76.0.1, 0.76.0.2): kageant.exe used with "--encrypted" flag crashes when queried for keys

### ISSUE THREAD

**Issue by leo-liar** [cyd01/KiTTY#333] opened 2021-11-09 20:14 UTC
Hey there,

using the *--encrypted* flag for `kageant.exe` in the new version **v0.76.0.1** to load keyfiles without decrypting them beforehand leads to a crash of `kageant.exe` when trying to establish a connection that uses one of those encrypted keys.

It doesn't matter if I start the connection from `kitty.exe` or from `kageant.exe` (e.g. via their right-click-menus), as soon as the key is requested instead of asking me to enter the password, `kageant.exe` stops working.

EDIT:
I just tried checking my old keyfiles with `kittygen.exe` and it crashed with the following error when attempting to load them ...

![image](https://user-images.githubusercontent.com/25538015/141001935-483bd3e5-6f06-43b5-9a16-61dc8c623736.png)

I don't know if these errors are related or if these are separate bugs.

~~EDIT 2:~~
~~Loading the keys encrypted (standard behaviour, without the flag) works fine.~~

EDIT 3:
~~Will have to check later on another machine to be sure, but apparently `kageant.exe` even crashes if I do decrypt upon starting.~~
Just confirmed it, `kageant.exe` crashes even without the *--encrypted* flag, even if there are no password protected key files (only unprotected ones) loaded at all.

EDIT 4: (Sorry for all the edits!)
Unprotected key files *can* be opened with `kittygen.exe` v0.76.0.1, it only crashes with password protected key files. `puttygen.exe` (v0.76 *64-bit x86*) opens both kind of key files without problems.

**Comment by kissglay** [comment] 2021-11-10 03:39
Having same issue. plus #335

**Comment by cyd01** [comment] 2021-11-12 11:45
Did you test it with original PuTTY ? The crash come from a section I did not modify. So that I don't really know what happened.

**Comment by leo-liar** [comment] 2021-11-12 12:59
Sorry, tried it with the original `pageant.exe` (from [here](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)) and it worked as supposed (a passwort input field popped up). Didn't even need to try your fixed one.

**Comment by dlong500** [comment] 2021-12-08 18:34
What is the status of this?  I'm using kitty/kageant 0.76.0.2 and kageant seems very finicky.  Frequently when a connection attempts to use a key stored by kageant the agent crashes (and of course the use of the key fails).  This can occur even if the added key is not encrypted.  What is puzzling is that it only sometimes crashes.  I never had any issues until the 0.76.0.1+ versions.

**Comment by leo-liar** [comment] 2021-12-09 20:53
No change so far. I get crashes every time whether I use encrypted keys or not, regardless of the _--encrypted_ flag.

As a workaround I'm using the most recent versions of `pageant.exe` and `puttygen.exe` (having them renamed `kageant.exe` and `kittygen.exe` respectively).

**Comment by Fredrik-69** [comment] 2021-12-11 08:46
I can confirm the same problem exist with the portable version (0.76.0.2). It crasches when trying to use the builtin agent, like:

kitty_portable.exe -runagent -pass "My_Password" "Key1" "Key2" -c kitty_portable.exe -launcher

**Comment by dlong500** [comment] 2021-12-29 19:25
@cyd01 Kageant 0.76.x is unusable in its current form; it's frequently crashing when trying to use any connection.  Can we pin down what the actual problem is?  I'm happy to help test something.  For now I'm going to have to roll back to 0.74 for my production use.

**Comment by cyd01** [comment] 2021-12-31 08:43
Can you check the 0.76.0.3 version please ?

**Comment by kissglay** [comment] 2021-12-31 08:49
On 0.76.0.3
"Add Key (Encrypted)" still crashes, without the intended dialog box asking for the passphrase.
"Add Key" no longer crashes.

**Comment by dlong500** [comment] 2021-12-31 08:55
I'll switch to 0.76.0.3 now and see what happens.  Since the problem was intermittent it may take a day or two to see if there is any difference on my end.  Thanks for looking into this.

**Comment by kissglay** [comment] 2022-01-02 17:49
On 0.76.06
It doesn't crash anymore, encrypted or not, all working as intended.
Thx.

**Comment by cyd01** [comment] 2022-01-03 13:50
Ok let's close it.

**Closed by cyd01** 2022-01-03 13:50 UTC

**Comment by leo-liar** [comment] 2022-01-06 02:25
I just had time to check version 0.76.0.3 now and it works as intendet! Thank you very much!!
