### ISSUE TITLE
Mouse support broken

### ISSUE THREAD

**Issue by Dubbeldrank** [cyd01/KiTTY#235] opened 2020-10-10 08:42 UTC
I use weechat with mouse support, but since 0.74.2.5 it's broken. I know it might no be within your scope to test, but i just want to inform you about it. Switched back to 0.74.2.4.

**Comment by eladeyal-intel** [comment] 2020-10-10 16:03
I have a host with tmux v2.3 which is configured in a way that clicking a pane selects it.

in kitty 0.74.2.4 this works. in 0.74.2.5 it does not.

tmux supports other mouse controls - and these work well.

**Comment by cyd01** [comment] 2020-10-10 20:22
Can you test this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by IcerOut** [comment] 2020-10-10 21:37
I had the same issue as above (mouse support broken, I personally noticed it in vim).
I just checked the test build you posted and the issue is fixed in that one.

**Comment by cyd01** [comment] 2020-10-10 21:49
Ok I'll release it

**Closed** 2020-10-10 22:03 UTC

**Comment by Dubbeldrank** [comment] 2020-10-10 22:11
Fix confirmed! I'm bad at reporting, i should've mentioned i also use tmux. Thanks!
