### ISSUE TITLE
New version Kitty has several issues

### ISSUE THREAD

**Issue by PabitraPati** [cyd01/KiTTY#232] opened 2020-09-24 13:36 UTC
1 - sometimes console doesn't show the prompt for the line where cursor is, not shown. The prompt area is blank
                                        (Refer KItty-prompt1.png & KItty-prompt2.png)

2 - Sometimes the current console is unable to scroll up the past outputs and writes over it. That is, from the top you have your command prompt and cursor, and below that your previous output. As you press enter, one previous output disappears and your current command prompt writes (Refer KItty-overwrite.png)

3- Sometime, even though your command has been completed and your console is not in focus, output is not shown. You focus back to the console, and press Enter, then your console shows the output which it should have been printed as the command finished.

These issues were not there on previous versions.

![KItty-prompt1](https://user-images.githubusercontent.com/8273486/94152295-0674f100-fe99-11ea-9073-8e9b3a44aa68.png)
![KItty-prompt2](https://user-images.githubusercontent.com/8273486/94152315-0a087800-fe99-11ea-88f7-0747f36c98c4.png)
![KItty-overwrite](https://user-images.githubusercontent.com/8273486/94152327-0bd23b80-fe99-11ea-95d5-a971e630caa1.png)

**Comment by Lamieur** [comment] 2020-09-27 12:29
I'm using 0.73.2.3p - that's the last one that does not have issue #3 and has working reconnection, but issue #1 is already there. I came here exactly to check if that's been fixed in the mean time, but apparently not.

So, #3 I've seen introduced in some newer version (0.74.x?), #2 must be even newer, but #1 is old, wish I had time to bisect when that appeared, it's the most frustrating thing!

You're embedding KiTTY into MTPuTTY, while I'm using SuperPuTTY - so although we're using different tabbed interfaces, this embedding seems to be the common thing.

The issue happens every time when there's text being output to the terminal and the KiTTY window/tab is not foreground.

It manifests itself only when I'm in another SuperPuTTY tab (with another KiTTY) - when something is supposed to happen on the screen, the one in the background won't do anything, other than draw a new cursor.

It's trivial to reproduce, just run something like "sleep 1; ls" and switch to the next tab before the output is printed. Then go back and the terminal is in this state every time.

Scrolling around produces funky artifacts - there's some kind of optimization, when it doesn't update the text it thinks it doesn't need to, so you get parts of different commands' output mixed together. Selecting stuff with a mouse is better at redrawing the actual screen contents, but of course I was about to paste something into that terminal and now it's overwritten with selection ;) There's also resizing the window, that works, but not what I wanted :)

I'm looking for some kind of full terminal redraw shortcut - does KiTTY have one? :)

**Comment by pepoluan** [comment] 2020-10-10 15:13
> I'm looking for some kind of full terminal redraw shortcut - does KiTTY have one? :)

Try using the `reset` command.

On Linux, whenever my display gets funky, I'll use `reset` to make it, well, reset the terminal.

Needless to say it will also clear whatever being displayed, though.

**Comment by Lamieur** [comment] 2020-10-10 15:42
Yeah, I was looking for a refresh, not a clear screen, and certainly not a full reset :)

It's for situations when I'm coming back to the tab when some longer job is outputting stuff periodically, it can be in color, it can be a progress bar with cursor at specific column, or it may have finished and I'm in the middle of the line after a prompt - reset breaks all that.

Of course, I wouldn't need to look for work-arounds if we knew what causes this, to help fix the damn thing :)

**Comment by lavdnone** [comment] 2020-11-20 02:14
is the klink part the same as https://github.com/cyd01/KiTTY/issues/3 ?

**Comment by cyd01** [comment] 2021-12-31 09:27
Issue closed due to inactivity

**Closed by cyd01** 2021-12-31 09:27 UTC
Labels: bug
