### ISSUE TITLE
Reconnect hangs on password entry

### ISSUE THREAD

**Issue by meilon** [cyd01/KiTTY#197] opened 2020-07-03 10:38 UTC
I just updated to the most current release (0.74.0.2) and for some servers, the reconnect doesn't work. It hangs in the password entry, but doesn't seem to accept entering the password. 
I jumped between versions and the last time this works is 0.73.2.3, in 0.73.2.4 it stops working.
The difference between still working versions after that is, that the login process is different. For working hosts it looks like that:

```Using username "admin".
Keyboard-interactive authentication prompts from server:
| admin's password for keyboard-interactive method: [I enter my password]
End of keyboard-interactive prompts from server

xxx > exit
[session disconnects, I click into the window to start reconnecting]
Using username "admin".
Keyboard-interactive authentication prompts from server:
| admin's password for keyboard-interactive method:
Send automatic password (Using keyboard-interactive authentication)
End of keyboard-interactive prompts from server

xxx >
```
and for hosts where it doesn't:

```Using username "admin".
Keyboard-interactive authentication prompts from server:
| Password: [I enter my password]
Send automatic password (Using keyboard-interactive authentication)
End of keyboard-interactive prompts from server

yyy > exit
logout
[session disconnects, I click into the window to start reconnecting]
Using username "admin".
Keyboard-interactive authentication prompts from server:
| Password:
```

What do you need from me to provide you with further details to debug this problem? It is consistent for a series of switches and appliances, so there must be something in common.

**Comment by cyd01** [comment] 2020-07-06 13:25
What it is strange in the second is:
```
| Password: [I enter my password]
Send automatic password (Using keyboard-interactive authentication)
```
If you entered the password, KiTTY sould not try "automatic password" !
Are you sure you don't have a password already stored in configuration ?

**Comment by meilon** [comment] 2020-07-07 05:42
Yes, I'm 100% sure. I downloaded the latest portable to a blank directory and just entered the IP of a device where this issue appears and set the "Close window on exit" to "Never". Same output. I also tried it with pageant closed, still nothing changed.

**Comment by Dibbyo456** [comment] 2020-07-07 14:15
Can confirm the same issue.

**Comment by cyd01** [comment] 2020-07-07 16:34
It will be difficult to fix without being able to reproduce.

**Comment by meilon** [comment] 2020-07-08 14:00
I don't know if @Dibbyo456 can confirm, for me it works in 0.73.2.3 and stops working at 0.73.2.4. The [diff](https://github.com/cyd01/KiTTY/compare/v0.73.2.3...v0.73.2.4) doesn't show that much, but as long as other dependencies didn't change (like a mingw update and libraries) one of these changes must be it. 
The bad thing is, with the 0.74.0.2, it doesn't even work with some devices still working with 0.73.2.4
I noticed I can't interact with the console window itself during this hang (like selecting text and ctrl+right click), but the menu clicking on the window icon still works:
 * Close+Restart just prompts me for the password again, same lockup so I still can't enter something
 * Duplicate Session opens a new window with password prompt, but there I can login


I did a full log with packets, and the last entry is 
```
Incoming packet #0x7, type 60 / 0x3c (SSH2_MSG_USERAUTH_INFO_REQUEST)
  00000000  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01  ................
  00000010  00 00 00 0a 50 61 73 73 77 6f 72 64 3a 20 00     ....Password: .
```

So it doesn't seem to be SSH protocol related. The console window just doesn't want to accept any input and/or use the password I entered for automatic re-login (like it works for linux servers, still no saved credentials in the configuration)

**Comment by meilon** [comment] 2020-08-07 09:06
Problem still exists with v0.74.0.3, also possible duplicates with Issues #211 and #201

**Comment by cyd01** [comment] 2020-08-07 16:51
I've just reverted a few things. Can you check this [build](http://www.9bis.net/kitty/files/kitty-debug.exe) please ?

**Comment by meilon** [comment] 2020-08-11 08:17
Okay, this one is weird!  For the devices it didn't work before I can now enter the password again, though I expected automatic login with the previous password.
For the devices it worked before it tries to automatically login, but can't, and I get blocked by the endpoint for wrong password attempts if I try this to often:
```
> exit
Using username "admin".
Keyboard-interactive authentication prompts from server:
| admin's password for keyboard-interactive method:
|
Send automatic password (Using keyboard-interactive authentication) [getting disconnected immediately, hitting enter to reconnect]
Using username "admin".
Keyboard-interactive authentication prompts from server:
| admin's password for keyboard-interactive method:
|
End of keyboard-interactive prompts from server
[now logged in again]
```

**Comment by meilon** [comment] 2020-08-12 12:42
With the just released 0.74.0.4 the same issues I mentioned above still exist. While KiTTy doesn't hang anymore, there is still an issue with the automatic password function. The weird issue is, that I don't save the password in the portable session files, so it somehow gets saved after the login and remembered incorrectly after connecting again. And this gets used/not used depending on the endpoint. There only is the user name set.

And I just tried 0.74.0.4 portable in a blank directory again, it makes a difference if auto username is set or not. With it set I just get disconnected, with it not set I get an access denied error.

**Comment by meilon** [comment] 2020-10-07 09:47
Same happens with the 0.74.2.4 release

**Comment by meilon** [comment] 2020-12-03 07:56
I've tested most releases since then and finally 0.74.3.4 seems to have fixed the bug! Might be #243 related.

@Dibbyo456 How's it working for you?

**Comment by cyd01** [comment] 2020-12-04 17:23
Pretty sure it is #243 related.
I close the issue.

**Closed by cyd01** 2020-12-04 17:23 UTC

**Comment by chrapuch** [comment] 2020-12-18 08:29
I'm afraid the issue is still occurring. KiTTY window is not accepting keyboard input (or selecting text with a mouse) after re-connecting. It just hangs on password input. v0.74.3.5
