### ISSUE TITLE
Unable to login with 2FA

### ISSUE THREAD

**Issue by c-rilaun** [cyd01/KiTTY#49] opened 2019-09-13 08:40 UTC
If 2FA is enable (with Google pam for example), you are unable to type the verification code. 
Works fine with Putty, maybe just a settings ?

Screenshot : [https://ibb.co/Vg57p3g](https://ibb.co/Vg57p3g)

**Comment by c-rilaun** [comment] 2019-09-13 09:38
Same issue as #24 - sorry, thought nobody repport this.

**Comment by cyd01** [comment] 2020-12-18 17:15
Maybe solve with 
- #243 
- #245

**Comment by cyd01** [comment] 2020-12-18 17:17
Duplicate of #243 
Duplicate of #245

**Closed** 2020-12-31 12:28 UTC
Labels: duplicate
