### ISSUE TITLE
Config window not opening when using menu "New session" from dead session's window

### ISSUE THREAD

**Issue by netadair** [cyd01/KiTTY#164] opened 2020-04-22 11:00 UTC
When using the menu entry "New session" from a dead session's window, the config screen does not open. When this happens, even after the session is restarted in the window, the menu entry still does not work.
 This happens using 0.73.2.11p .

**Comment by netadair** [comment] 2020-04-22 20:14
PS: This happens also with other windows with alive sessions.
Workaround: starting new kitty process

**Comment by EqUaTe** [comment] 2020-05-24 07:14
@netadair this works for me with 0.73.2.15 & 0.73.2.16.
Please update and then say still an issue - if not, please close this :-)

**Comment by lars18th** [comment] 2021-01-26 08:14
Hi @netadair and @cyd01 ,

In last releases I don't see this problem. And I re-checked it some minutes before.
So please, check if this issue can be closed.

Regards.

**Comment by cyd01** [comment] 2021-03-01 10:24
It can't reproduce.  
When choosing "New session", he configuration box shows up as expected.

**Closed by cyd01** 2021-03-01 10:24 UTC
Labels: bug, good first issue, unreproducible
