### ISSUE TITLE
Hangs on connection open/close

### ISSUE THREAD

**Issue by bobvandevijver** [cyd01/KiTTY#22] opened 2019-06-06 18:11 UTC
It seems that with the release of Windows 10 1903 kitty sometimes hangs when opening a session: the terminal window opens unresponsive (and is empty), and after a few seconds it proceeds as you  would normally expect. 

Secondly, when losing a session, it previously was possible to use any key to reconnect, but it does not seem to respond to that anymore (it actually warns when closing that the connection would still be activity, while the taskbar icon clearly indicates the connection is no longer there).

**Comment by lars18th** [comment] 2019-06-10 15:24
Hi @bobvandevijver ,

> Secondly, when losing a session, it previously was possible to use any key to reconnect, but it does not seem to respond to that anymore (it actually warns when closing that the connection would still be activity, while the taskbar icon clearly indicates the connection is no longer there).

This is the same bug commented in #23 , futhermore the same described in #15 .

If we can provide more feedback then @cyd01 perhaps can fix it.

Regards.

**Comment by bobvandevijver** [comment] 2019-06-14 12:53
While the second part is indeed now solved with #23, the first part (hanging on opening) still holds. Might have something to do with port forwarding?

**Comment by lars18th** [comment] 2019-06-14 13:52
Hi,

As I described in https://github.com/cyd01/KiTTY/issues/23#issuecomment-501669383 when using TCP tunnels (or Proxies) for the connections, the session enters in a stalled state. I recommend to add some "close&reconnect" as this will simplifies a lot this type of problems.

**Comment by bobvandevijver** [comment] 2019-06-18 17:19
This issue also happens with connection that do not use any tunnels or proxies.

**Comment by lars18th** [comment] 2019-06-19 06:51
> This issue also happens with connection that do not use any tunnels or proxies.

In this case I recommend the simple "close&reconnect" command as the most simple workaround.

**Comment by bobvandevijver** [comment] 2019-06-19 07:03
That won't work, as it completely hangs ("this application is not responding"). At the moment it does respond, the connection is opened correctly.

**Comment by lars18th** [comment] 2019-06-19 07:24
> That won't work, as it completely hangs ("this application is not responding"). At the moment it does respond, the connection is opened correctly.

Hi @bobvandevijver ,

I recommend to _implement_ a _new_ "close&reconnect" command. It doesn't exist at time!

**Comment by bobvandevijver** [comment] 2019-06-19 16:13
Again, that will **never** work for this scenario. The application is completely **unresponsive**, Windows nags about it when clicking the window. It will never show any dialog on whatever input you provide to the window (not the ssh-session)!

**Comment by lars18th** [comment] 2019-06-19 16:53
> Again, that will **never** work for this scenario. The application is completely **unresponsive**, 

Ok, now I understand you. In my day work when the error appears the Menu of the KiTTY continues working. Only after using "Repeat key exchange" (when the connection is lost, but the session is not detected as closed) the KiTTY goes unresponsive.

I'm sure a bug exists in the handle of the session when a network error appears. 
I hope @cyd01 will found and fix it soon.

Regards.

**Comment by bobvandevijver** [comment] 2019-07-01 17:36
No, it is not fixed.

**Comment by thomasgg23** [comment] 2019-07-05 20:18
Can confirm that it's not fixed in 0.71.0.5.
Having the same issues in combination with Windows 10 1903

Also the problem is the same with the latest putty client and Windows 10 1903.

**Comment by thomasgg23** [comment] 2019-07-05 20:59
I think this one is a windows related problem.
I tried the linux ubuntu image from the windows app store and did a ssh session to a linux server on the internet. After a short time the session hung up and the ssh client terminated.

**Comment by thomasgg23** [comment] 2019-07-05 21:03
and even the build in client you can open with a cmd line hung up.

perhaps @bobvandevijver you can verify that with the build in client on the windows command line

**Comment by bobvandevijver** [comment] 2019-07-07 19:54
@thomasgg23 Might well be the case. I also see other network glitches..

**Comment by lars18th** [comment] 2019-07-16 19:29
Hi @thomasgg23 ,

Please, check if the problem continues in the new 0.71.0.6p release.

**Comment by bobvandevijver** [comment] 2019-07-19 06:26
Nope, 0.71.0.6 still has the same problem

**Comment by thomasgg23** [comment] 2019-07-19 09:06
Still same behavior with 0.71.0.6p. 
I will continue the tests on the weekend with multiple vpn and servers.
I had three sessions this morning which worked flawless and one session which immediately hung after a few seconds. I really think this isn't a problem with KiTTY

Will continue to watch on the weekend.

**Comment by bobvandevijver** [comment] 2019-08-23 05:33
I seem to have no issues after a fresh restart of the laptop, but after it has been in modern standby, the connection hangs on start.

**Comment by lars18th** [comment] 2019-12-20 14:32
Hi @bobvandevijver ,

Last version resolves your problem?

**Comment by thomasgg23** [comment] 2019-12-20 15:06
For me it seems to be resolved

**Comment by lars18th** [comment] 2019-12-20 15:21
> For me it seems to be resolved

Then I suggest to the original author and to @cyd01 to _close_ this issue.
It will be interesting to do some cleaning of the issues. :smile:

**Comment by bobvandevijver** [comment] 2019-12-20 15:28
I want to test it first, which I can probably do tomorrow. If satisfied, I will close it :)

**Comment by bobvandevijver** [comment] 2019-12-22 09:19
Issue still seems to be there, but a lot less frequent. I will try to figure out whether we can blame Windows and the networking stack for this, as it mostly seems to happen after modern standby.

**Comment by lars18th** [comment] 2020-02-12 11:02
Hi @bobvandevijver ,

Please, try version 0.73.2.3. I feel the issue is fully resolved.

Regards.

**Comment by bobvandevijver** [comment] 2020-02-12 11:09
I cannot try it due to #105, that needs to be resolved first.

**Comment by lars18th** [comment] 2020-02-12 13:19
> I cannot try it due to #105, that needs to be resolved first.

Hi @bobvandevijver ,

The issue #105 will never be solved. The main developer can't do anything to resolve this problem. The true is that the McAfee software is doing wrong. As it detects an unsigned binary _and_ this binary is a fork of a PuTTY, then it marks it as a malware. But it isn't. If you want to solve it, then write to McAfee. My recomendation is to disable it.

Please, someone other can check the last version? We need to know if the problem is fixed.

Regards.

**Comment by bobvandevijver** [comment] 2020-02-13 10:07
First off all, that's not how antivirus works, and yes, the developer can do something about it. Secondly, I'm not using McAfee. Thirdly, the uncompressed version has no issues, so I tested now with that one.

The issue still persist.

**Comment by lars18th** [comment] 2020-02-13 10:22
> First off all, that's not how antivirus works, and yes, the developer can do something about it. Secondly, I'm not using McAfee. Thirdly, the uncompressed version has no issues, so I tested now with that one.

OK @bobvandevijver , then please explain what the developer can do to overcome the issue. Personally I don't have any idea about how to resolve the problem. And I feel that @cyd01 doesn't know it either!

Regards.

**Comment by lars18th** [comment] 2020-03-18 08:06
Hi @bobvandevijver ,

The issue of the false-positive malware detection is commented in #115 . I suggest to post in this thread any comments than can help to solve this problem.

Regarding the hangs on reconnection @thomasgg23 has commented that from him the problem has gone in the last versions. Futhermore, some recent enhancements are incorporated in the last version regarding the reconnection part. The only missing funciton at time is the forwarding restart.

So, I suggest to @bobvandevijver or @cyd01 to close this issue... if you think that this problem is solved (almost partially and no referenced in other issues). You agree? :wink: 
Regards.

**Comment by bobvandevijver** [comment] 2020-03-18 11:55
I wont close this, as it is not resolved.

**Comment by lars18th** [comment] 2020-03-18 12:38
> I wont close this, as it is not resolved.

Please, can you explain what is not resolved?

**Comment by bobvandevijver** [comment] 2020-03-19 07:36
I'm sorry @lars18th, I was under the assumption that your knew what this ticket is about. Maybe you should stop commenting if you do not have anything useful to add. Repeating the same question is not going to solve this problem by some sort of magic.

KiTTY still hangs when opening a connection, which is most reproducible after a longer modern standby session. Other SSH clients (such as in WSL Debian) do not have this problem.

**Comment by cyd01** [comment] 2020-07-07 18:05
Not reproduced for a while.

**Closed by cyd01** 2020-07-07 18:05 UTC

**Comment by lfdominguez** [comment] 2022-07-13 15:13
I'm using kitten ssh, but seems the ssh master process continue running and don't allow that close the terminal.
