### ISSUE TITLE
Feature request: CTRL+HOME / CTRL+END parsing

### ISSUE THREAD

**Issue by MrM40** [cyd01/KiTTY#92] opened 2020-01-10 09:34 UTC
Is seems CTRL+HOME / CTRL+END are not parsed on to the server (neither in puTTY).
E.g. to jump to the beginning and end of a document.
Would be nice to have support for these keys.

**Comment by lars18th** [comment] 2020-02-12 10:47
Hi @MrM40 ,

Please try this fork of KiTTY: https://github.com/adizero/KiTTY
If this works then...

**Comment by MrM40** [comment] 2020-02-12 12:19
Thanks for the link.
Cannot find any binaries :-( (maybe I'll try to compile myself one day when I have more time).
But I can confirm newest version of cyd01/KiTTY, as per today 0.73.2.3p,  doesn't seem to support CTRL+HOME/END either as e.g. Chrome SSH (but it has other bugs and quirks)

**Comment by MrM40** [comment] 2020-03-06 07:45
That would really be great! I'm in the middle of creating a console file-browser where I also need this keystroke to jump to the first and list file/folder, whereas HOME/END just jump to the first and last file/folder in the current window.

But I cannot get it to work in the new beta build, although something did change :-)
It seems CTRL+HOME/END now directly move to the beginning/end of the console buffer, not parsing the keystroke on to the console application (not sure if this is true, don't know how it actually works behind the scene, but that's how it looks).

E.g. if I push CTRL+X this is parsed on to the console application as the following 
![ctrlx](https://user-images.githubusercontent.com/16258063/76062004-0822aa00-5f85-11ea-822d-50882866e8cd.png)
(debugging in Visual Studio, .Net Core)

If I push CTRL+HOME nothing if parsed on at all.

It doesn't work in the Nano editor either, e.g. CTRL+HOME should be parsed on to Nano which will move focus to the beginning of the document. But Nano never sees CTRL+HOME.

I'm using Debian 10 and my keyboard settings:
![keyb](https://user-images.githubusercontent.com/16258063/76062477-11f8dd00-5f86-11ea-8ef9-746f3e194231.png)

**Comment by cyd01** [comment] 2020-03-07 22:33
Ok I've mix two different requests. I'm sorry. I've reverted the changes. And I will look at the fork https://github.com/adizero/KiTTY.

**Comment by lars18th** [comment] 2020-03-09 10:01
Hi @cyd01 ,

You're doing a huge effort and we appreciate anything you done. Thank you!
However, if you need anything from us, please ask.

Futhermore, I suggest you to open new branches when you release a new beta. Then it will be easy to report/test/fix/etc of the code you've changed. A different branch doesn't interfere with the main project, and you can merge the changes if you want. Please, try it!

Regards.

**Comment by lars18th** [comment] 2020-03-13 08:22
I feel this is implemented in the last version, right?
Then close the issue, please.

**Comment by MrM40** [comment] 2020-03-13 08:30
My message from 7 days ago shows it's not.
Or am I missing something?

**Comment by lars18th** [comment] 2020-03-13 08:46
> My message from 7 days ago shows it's not.

Right.

> Or am I missing something?

The version v0.73.2.6 published some hours ago. Please, check it: https://github.com/cyd01/KiTTY/releases

**Comment by MrM40** [comment] 2020-03-13 09:01
Ahh....nice :-)
I'll check it out, thanks

**Comment by MrM40** [comment] 2020-03-13 09:55
Jep, it woooooorks :-)

But I think a new bug is introduced.
A single END press now result in a ESC key-stroke. 
![END](https://user-images.githubusercontent.com/16258063/76610399-20f90580-6519-11ea-9f21-aa06b0ac2072.png)

**Comment by lars18th** [comment] 2020-03-13 10:34
Hi @MrM40  ,

> Jep, it woooooorks :-)

:tada: 

> But I think a new bug is introduced.
> A single END press now result in a ESC key-stroke.

OK. Then @cyd01 will need to review the code.
However, please check if any other key is mapped incorrectly.

Regards.

**Comment by MrM40** [comment] 2020-03-13 10:42
Any other keys seems to be mapped correctly

**Comment by lars18th** [comment] 2020-03-13 10:58
Please @adizero , can you check if this problem is in your "native" version?

>> A single END press now result in a ESC key-stroke.

**Comment by adizero** [comment] 2020-03-13 22:35
I suspect HOME key will not work correctly for him as well. It is the usual problem of HOME and END keys. If you look at the /etc/inputrc in Linux you'll find it supports 4 different encodings of home/end:

"\e[1~": beginning-of-line
"\e[4~": end-of-line
"\e[7~": beginning-of-line
"\e[8~": end-of-line
"\eOH": beginning-of-line
"\eOF": end-of-line
"\e[H": beginning-of-line
"\e[F": end-of-line

I have used \e[H and \e[F for XTerm settings, but that is not correct. It is supported by bash/vim or any gnu readline program so I did not realize any problem with it. But now checking with XTerm I see that XTerm emits \e[4~ (and not \e[F) for END keys without modifiers. But XTerm sequence for SHIFT+END is \e[1;2F ALT+END is \e[1;3F CTRL+END is \e[1;5F SHIFT+CTRL+END is \e[1;6F CTRL+ALT+END is \e[1;7F.

It should be one line fix. I will try to do it today.

**Comment by lars18th** [comment] 2020-03-14 07:24
> It should be one line fix. I will try to do it today.

Great! Thank you for your good work! :+1:

**Comment by cyd01** [comment] 2020-03-14 09:48
Thanks

**Comment by MrM40** [comment] 2020-03-29 14:39
(related to [#134](https://github.com/cyd01/KiTTY/pull/134))
In 0.73.2.8 CTRL+HOME/END now works :-)
But we still have an issue with SHIFT+END
![SHIT_END](https://user-images.githubusercontent.com/16258063/77851846-8c122f80-71db-11ea-8916-bcf28540c0bb.png)

**Comment by lars18th** [comment] 2020-03-29 17:13
Thank you @MrM40 for reporting it.

Please @adizero can you check it? You're the main developer of this part, so plase comment about this.

Regards.

**Comment by MrM40** [comment] 2020-03-29 17:28
FYI same problem in version 73.2.6 when just pressing END, it also parsed Escape (see above).
It was just fixed within one of the latest versions.

**Comment by adizero** [comment] 2020-03-31 05:15
There is no difference between home key and end key handling in the code. I am surprised that only one of them does not work for you. For me it behaves exactly like xterm terminal.

Can you try with The Home and end Keys configuration set to Standard ?

If you are on Linux can you show the output of `showkey -a` while pressing home/shift+home/ctrl+home/end/shift+end/ctrl+end from KiTTY ?
Try the same via xterm terminal.

Paste the output. Thanks.

**Comment by MrM40** [comment] 2020-03-31 07:11
`showkey -a` on debian buster, 
![Showkey](https://user-images.githubusercontent.com/16258063/77995958-030b0d80-732d-11ea-8ddc-542d3f48b6fd.png)
I just tracked all the key-codes in dotnet and the actual result is this (before I just tracked the first key-code):
![dotnet](https://user-images.githubusercontent.com/16258063/77996579-2a160f00-732e-11ea-946b-047876648b52.png)

Could it be a timing issue, either in dotnet or in kitty when pressing SHIFT+END?

**Comment by MrM40** [comment] 2020-03-31 07:47
It just seems likely to me that the "SHIFT+END" issue is related to the issues in 73.2.6 where pressing "END" also resulted in and Escape code, but that got fixed in one of the later Kitty versions.

**Comment by lars18th** [comment] 2020-03-31 08:07
Hi @MrM40 ,

I suggest to prepare a simple guide to reproduce the issue. Then @cyd01 can execute the same steps in his environment and check the code. Example:

1. Remote host: Debian Buster 64bit.
2. Open KiTTY in portable mode _without_ any INI file.
3. Open one SSH to the remote host with this configuration of session/keyboard based on defualt config: ...
4. Execute these commands in shell: ...
5. Close KiTTY.

I hope this can help to isolate and trace the error.
Regards.

**Comment by MrM40** [comment] 2020-03-31 08:41
Yes, I agree. 
But I'm thinking if @cyd01 get the same key-codes as I using `showkey -a` the issue must be related to dotnet core 2.2 together with Kitty and then I assume dotnet core + debug tool (in my case Visual Studio 2017) must be include in the test-setup, and I wonder if @cyd01 find it fun to establish such a setup :-P
I might be helpful here setting up VMs you can logon to (Windows+VS and Buster)
Before before taking these steps,  could you guys confirm if the issue couldn't be fixed the same way the "END" issue was fixed as few days ago? They sure have the same smell to it.
I know @adizero said the code is the same as `SHIFT+HOME`, but still.

**Comment by MrM40** [comment] 2020-03-31 08:46
On 2nd thought I can just create a dotnet tool like `showkey`, then dotnet debug tool is not necessary. Let me know if needed.

**Comment by lars18th** [comment] 2020-03-31 09:35
Hi @MrM40 ,

I do the test with `showkey -a` with the last KiTTY version in a Debian 7 and in a WSL 1.0 Debian session. In both cases I obtain the same results, and they are identical to the table posted before.

So, I feel is a problem only with "donet core". Then if you can prepare a precompiled tool like `showkey` in this case we can test it.

Regards.

**Comment by MrM40** [comment] 2020-03-31 10:24
Depending of your prefered archive format:
[showkeydotnet.tar.lz](http://wit.dk/temp/showkeydotnet.tar.lz) (31KB)
[showkeydotnet_selfcontained.tar.lz](http://wit.dk/temp/showkeydotnet_selfcontained.tar.lz) (include dotnet core 2.2 runtime files, portable, 20MB)
[showkeydotnet.7z](http://wit.dk/temp/showkeydotnet.7z) (contain both, 19MB)
Compile target: Linus x64

**Comment by lars18th** [comment] 2020-03-31 10:39
Hi @MrM40 ,

I tested the selcontained version in Linux with the last version of KiTTY. And it's true, keys `HOME`, `END`, `SHIFT+HOME` work, but `SHIFT+END` is inconsistent:
```
Key: Escape
KeyChar: 0
Modifier: 0
--------------
Key: D1
KeyChar: 0
Modifier: 0
--------------
Key: 0
KeyChar: 0
Modifier: 0
--------------
Key: D2
KeyChar: 0
Modifier: 0
--------------
Key: F
KeyChar: Shift
Modifier: Shift
--------------
```

However, I'm not sure if the problem is KiTTY or the dotnet core.
Can someone check this tool is a real XTerm in a Linux X11 session, please?

**Comment by lars18th** [comment] 2020-03-31 10:53
Hi @MrM40 ,

Executing your `publish_selfcontained/showkeydotnet` inside a Cygwin SHELL with a SSH session to the same Debian server, the results are worse!

I feel the problem is with the dotnet core... I recomend that you test your tool in other environments not using KiTTY and share your results. I suspect the results will not be what you expect.

Regards.

**Comment by cyd01** [comment] 2021-12-31 09:28
Issue closed due to inactivity

**Closed by cyd01** 2021-12-31 09:28 UTC
Labels: enhancement
