### ISSUE TITLE
'chanlog' on website

### ISSUE THREAD

**Issue by bish0polis** [cyd01/KiTTY#188] opened 2020-05-23 23:57 UTC
On several pages on the website at https://www.9bis.net/kitty , I see references to 'chanlog'.   It maybe should be 'changelog', and a search/replace in there may effectively fix it all up.

**Comment by EqUaTe** [comment] 2020-05-24 07:14
Dupe of #122

**Closed** 2020-05-24 13:52 UTC

**Comment by DumbJoe** [comment] 2022-08-26 03:06
two years later looks like they either dont care or forgotten about it...or maybe that's their stylized "changelog"?
